// Generado por web_i18n/i18n_rebuild.js (en) a partir de web/js/maps.js. No editar a mano: editar la memoria tm/en.json y regenerar.
const MAPS = {
 "map-fil-que-es": {
  "subject": "fil",
  "tema": "Philosophy · Topic 1",
  "title": "What is philosophy?",
  "md": "# What is philosophy?\n## Love of wisdom\n- *Philía* (love) + *sophía* (wisdom)\n- The philosopher **seeks** the truth, does not possess it\n- It arises from **wonder**, curiosity and doubt\n- ‘I know only that I know nothing’ (**Socrates**)\n## From myth to logos\n- Greece, **6th century BC**\n- **Myth**: a tale of gods; anthropomorphic, arbitrary, **dogmatic**\n- **Logos**: natural causes and **arguments**; **critical**\n- **Thales of Miletus** seeks the **arkhé**\n## Types of knowledge\n- **Common**: spontaneous, unreflective\n- **Scientific**: proximate causes; **partial**\n- **Philosophical**: ultimate causes; reality **as a whole**\n## Features of philosophical knowledge\n- **Rational** and **critical**\n- **Radical**: goes to the root\n- **Universal** and **systematic**\n- **Practical**: ethics and politics\n- **Open** and **historical**\n## The branches\n- **Metaphysics**: what being is, what exists\n- **Theory of knowledge**: what we can know\n- **Ethics** and **political philosophy**\n- **Aesthetics**, **logic** and **anthropology**\n## With the other kinds of knowledge\n- **Science**: data and experiments\n- **Religion**: faith and revelation\n- **Art**: works that make us feel\n- **Philosophy**: concepts and arguments\n## What it is for\n- Thinking for yourself\n- Reading and commenting on **texts**"
 },
 "map-filosofia-ciencia": {
  "subject": "fil",
  "tema": "Philosophy · Philosophy of science",
  "title": "Philosophy of science",
  "md": "# Philosophy of science\n## Central questions\n- What is **scientific knowledge**?\n- How is it obtained?\n- What distinguishes science from other kinds of knowledge?\n## Philosophy of physics\n- **Space and time** — Newton vs Leibniz; relativity; quantum theory\n- **Causality** — determinism vs indeterminism\n## Scientific epistemology\n- **Realism** — theories describe the truth\n- **Instrumentalism** — theories are tools\n- **Social construction** of knowledge\n- Proof: **induction**, **falsification** (Popper), Bayes’ theorem\n## Methodology\n- **Scientific method** — observation, hypothesis, experiment, theory\n- Classification: formal, physical, biological and social sciences\n## Philosophy of mathematics\n- **Platonism** — mathematical objects exist\n- **Nominalism** — they are only language\n- **Intuitionism** — they are a human construction\n## History of science\n- Revolutions: **Copernicus**, **Newton**, **Einstein**, quantum theory\n- **Galileo** — start of the scientific revolution"
 },
 "map-ser-humano": {
  "subject": "fil",
  "tema": "Philosophy · Topic 2",
  "title": "What is the human being?",
  "md": "# What is a human being?\n## Nature and culture\n- **Evolution** → **hominisation** (biological)\n- **Culture** → **humanisation** (learned)\n- Nature–culture dialectic; we are born ‘unfinished’\n## Culture, identity and diversity\n- **Socialisation**; personal and collective identity\n- **Ethnocentrism / relativism / interculturality**\n## Body and mind\n- **Dualism** — Plato (the soul’s prison); Descartes (res cogitans / res extensa)\n- **Monism / materialism** — we are body\n- Aristotle — the soul as the **form** of the body\n## Conceptions through history\n- Antiquity — **rational** and social animal\n- Middle Ages — creature in the image of God\n- Modernity — thinking subject (Descartes); **dignity** (Kant)\n- Contemporary — Marx (labour), Nietzsche, existentialism (**project** and freedom)\n## Consciousness, language and person\n- **Consciousness** and self-consciousness (introspection)\n- Symbolic **language**\n- **Person** — dignity; an end in itself\n## Personal identity\n- Ship of Theseus; **memory** (Locke); Hume; the narrative\n- **Transhumanism**\n## The meaning of existence\n- Absurd / transcendent / immanent / **giving meaning to oneself**"
 },
 "map-conocimiento": {
  "subject": "fil",
  "tema": "Philosophy · Topic 3",
  "title": "What can we know?",
  "md": "# What can we know?\n## Human knowledge\n- **Subject — object** relation\n- Degrees: **sensation → perception → concept** (abstraction)\n- The branch: **epistemology / gnoseology**\n## The sources of knowledge\n- **Rationalism** (Descartes) — reason; innate ideas\n- **Empiricism** (Locke, Hume) — experience; *tabula rasa*\n- **Criticism** (Kant) — experience + reason\n## Can we reach the truth?\n- **Dogmatism** · **Scepticism** · **Relativism** · **Criticism**\n## The question of truth\n- Opinion (**doxa**) versus knowledge (**epistêmê**)\n- Theories: **correspondence**, coherence, consensus, pragmatic\n## Post-truth\n- Facts weigh less than emotions\n- Hoaxes, **fake news**, biases, echo chambers\n- Defence: **critical thinking** and checking sources\n## Scientific knowledge\n- **Formal** and **empirical** sciences (natural / social)\n- **Hypothetico-deductive method**; Popper (falsifiability), Kuhn (paradigms)\n## Science, technology and art\n- Science / technique / **technology**; ethical limits\n- **Women in science**"
 },
 "map-racionalismo-empirismo": {
  "subject": "fil",
  "tema": "Philosophy · Rationalism and empiricism",
  "title": "Rationalism vs. empiricism",
  "md": "# Rationalism vs. empiricism\n## The problem\n- Early Modern period: what is the **foundation of knowledge**?\n## Rationalism\n- Representative: **Descartes**\n- Source: **reason** — **a priori** knowledge\n- **Innate ideas**: God (res infinita), res cogitans, res extensa\n- **Dogmatism**: does not doubt the capacity of reason\n- **Universal and necessary** truths\n- **Deductive** method; model: **mathematics**\n## Empiricism\n- Representatives: **Locke** and **Hume**\n- Source: **experience** — **a posteriori** knowledge\n- Locke — the mind at birth is a **tabula rasa**\n- Hume — doubts **causality** (habit) → **scepticism**\n- General and **provisional** truths\n- **Inductive** method; model: **experimental science**\n## Synthesis: Kant\n- **Criticism** unites reason and experience\n- Redefines philosophy, metaphysics and science"
 },
 "map-fil-mito-logos": {
  "subject": "fil",
  "tema": "Philosophy · Topic 1",
  "title": "From myth to logos",
  "md": "# From myth to logos\n## The decisive step\n- Greece, **6th century BC**: philosophy is born\n- From explaining by **gods** to explaining by **reasons**\n## Myth (mythos)\n- Tales of **gods** with capricious wills\n- **Anthropomorphic and animist**\n- Transmitted by oral tradition\n- **Dogmatic**: accepted without discussion\n## Logos (reason)\n- Seeks **natural causes** and laws\n- Relies on **arguments**; has an author\n- **Critical**: can be discussed and revised\n## The first philosophers\n- They seek the **arkhé** (the first principle of everything)\n- **Thales of Miletus**: water\n- What is decisive: the **change of method**"
 },
 "map-fil-logica": {
  "subject": "fil",
  "tema": "Philosophy · Topic 4",
  "title": "Logic and argumentation",
  "md": "# Logic and argumentation\n## What logic studies\n- The **correctness** of reasoning\n- The **form** of thought, not its content\n- Founded by **Aristotle** (theory of the **syllogism**)\n## Propositions and arguments\n- **Proposition**: a statement that is true or false\n- **Argument**: **premises** that support a **conclusion**\n- To argue is to **give reasons**\n## Ways of reasoning\n- **Deduction**: **necessary** conclusion\n- **Induction**: from cases to the general; only **probable**\n- **Abduction**: the **best explanation** (Peirce)\n- **Analogy**: relevant similarities; risk of **false analogy**\n## Validity and truth\n- **Validity**: a property of the **form**\n- **Truth**: a property of the **content**\n- **Sound** = valid + true premises\n- An induction is not valid or invalid, but **strong** or **weak**\n## Formal and symbolic logic\n- **Frege**: first-order logic\n- **Connectives** and **truth tables**; **tautology** and **contradiction**\n- **Boole** and **Shannon**: from logic to **logic gates**\n- The liar **paradox**\n## Fallacies\n- They seem valid, but are not\n- **Formal** (the form) and **informal** (the content or the language)\n- *Ad hominem*, *ad populum*, straw man, false cause…\n- **Sophism** (on purpose) and **paralogism** (unintentional)\n## Analysing and dialoguing\n- Indicators; **implicit premises** (**enthymeme**)\n- **Burden of proof** and **principle of charity**\n- **Counterexample** and **reductio ad absurdum**\n- Reasoning, not **rationalising**\n## Defining and distinguishing\n- **Proximate genus** + **specific difference**\n- **Necessary** and **sufficient** condition\n- **Conceptual analysis**: what is lying?"
 },
 "map-fil-etica": {
  "subject": "fil",
  "tema": "Philosophy · Topic 5",
  "title": "The questions of ethics",
  "md": "# The questions of ethics\n## Ethics and morality\n- **Morality**: norms and values that hold in a community\n- **Ethics**: philosophical reflection on morality\n- ‘How should we live?’ (**Socrates**)\n- Levels: **normative**, **applied** ethics and **metaethics**\n## Freedom, the condition of morality\n- Without freedom there is no **responsibility**\n- **Autonomy** versus **heteronomy** (Kant)\n- **Incompatibilism** and **compatibilism**\n## Material ethics\n- They say what the **good** or the end is: **teleological**\n- **Aristotle**: *eudaimonia*; virtue as the **mean**\n- **Epicurus**: pleasure as *ataraxia*\n- **Utilitarianism** (Bentham, Mill): ‘the greatest happiness of the greatest number’\n## Kant’s formal ethics\n- **Deontological**: acting **from duty**\n- **Categorical imperative**: a maxim that can become a **universal law**\n- Humanity always as an **end** and never merely as a means\n## Are there moral truths?\n- **Objectivism**: moral facts that hold for everyone\n- **Subjectivism** and **cultural relativism**\n- **Non-cognitivism**: **emotivism** (Hume, Ayer)\n- Without possible criticism there is no **moral progress**\n## Moral judgement\n- **Piaget**: from **heteronomous** to **autonomous** morality\n- **Kohlberg**: three levels; the **Heinz dilemma**\n- **Gilligan**: the voice of **care**\n## Suspicion and borderline cases\n- **Nietzsche**: **master** and **slave** morality; **revaluation**\n- Utilitarianism put to the test: the **trolley** and the transplant\n- **Singer**: does it demand too much?\n## Applied ethics today\n- **Ethics of care** (Noddings, Tronto)\n- **Bioethics**: autonomy, beneficence, non-maleficence and justice\n- **Animal** ethics (**speciesism**) and the ethics of **AI**"
 },
 "map-fil-politica": {
  "subject": "fil",
  "tema": "Philosophy · Topic 6",
  "title": "Life in society",
  "md": "# Life in society\n## A political animal\n- **Aristotle**: *zoon politikón*\n- Whoever lives in isolation ‘is either a beast or a god’\n- Political philosophy asks how societies **should** be\n## Why does the state exist?\n- Ancients: the political community is **natural**\n- Moderns: an artifice, the **social contract**\n- The **state of nature**: a hypothesis, not a fact\n- Criticisms: **Hume** (conquest and utility) and **Kant** (an idea of reason)\n## The contract theorists\n- **Hobbes**: war of all against all → the **Leviathan**\n- **Locke**: natural rights → **liberal state** and right of resistance\n- **Rousseau**: **general will** → **popular sovereignty**\n## Power and legitimacy\n- **Power**: making others obey\n- **Legitimacy**: the right to rule\n- **Weber**: tradition, charisma and **rational-legal authority**\n## Justice\n- **Distributive** and **corrective** (Aristotle)\n- **Rawls**: **veil of ignorance** and **difference principle**\n- **Nozick**: entitlement and the **minimal state**\n- **Communitarianism** (Sandel): the goods we share\n## Forms of government\n- One, few, many: **monarchy**, **aristocracy**, **polity** (*politeia*)\n- Degenerate forms, in their own interest: **tyranny**, **oligarchy** and, for Aristotle, **democracy**\n- Modern democracy: **liberal**, **deliberative**, **participatory**\n- Threats: **tyranny of the majority**, **populism**, erosion from within\n## Rights and freedom\n- **Human rights** (1948): three **generations**\n- **Rule of law** versus **totalitarianism** (Arendt)\n- **Berlin**: **negative** and **positive** liberty\n## Imagining and extending the pact\n- **Utopias** (Plato, More) and **dystopias** (Huxley, Orwell)\n- **Feminism**: patriarchy, **sex and gender**, intersectionality\n- ‘One is not born, but rather becomes, a woman’ (**Beauvoir**)"
 },
 "map-fil-estetica": {
  "subject": "fil",
  "tema": "Philosophy · Topic 7",
  "title": "What is art?",
  "md": "# What is art?\n## Aesthetics\n- Reflects on **beauty**, **art** and **aesthetic experience**\n- From the Greek *aísthesis*: sensation (**Baumgarten**)\n- Contemplating something **for its own sake**, without seeking its use\n## Where is beauty?\n- **Objective** (classical): proportion, harmony, order and measure\n- Pythagoreans, **Polykleitos** (*Canon*), Augustine, Aquinas\n- **Subjective** (modern): the pleasure of the one who looks\n- Other categories: **the sublime**, the ugly, the tragic, the comic\n## The judgement of taste\n- **Hume**: the **competent critic**\n- **Kant**: **disinterested** and **universal without a concept**\n- **Purposiveness without purpose**; **free** and **dependent** beauty\n## Theories of art\n- **Imitation** (*mimesis*): representing reality\n- **Expression** (Romanticism): the author’s emotion\n- **Form** (formalism): composition, colour, rhythm\n- **Institutional** (Danto, Dickie): what the art world recognises\n## Art and truth\n- **Plato**: a copy of a copy; art **deceives**\n- **Aristotle**: *mimesis* and **catharsis**\n- **Hegel**: the ‘**end of art**’\n- **Heidegger** and **Gadamer**: the work opens up a world\n## Art, emotion and morality\n- Art **educates** the feelings\n- **Schiller**: **play** and aesthetic education\n- **Moralism** versus **autonomism** (‘art for art’s sake’)\n## Art and politics\n- **Committed art** versus **art for art’s sake**\n- **Benjamin**: fascism **aestheticises politics**\n- **Adorno**: the **culture industry**\n## The image today\n- **Duchamp** and the **readymade**\n- **Benjamin**: technical reproducibility and the loss of the **aura**\n- **Debord** (spectacle) and **Baudrillard** (**simulacrum**)\n- **Visual literacy**: looking critically"
 },
 "map-fil-metafisica": {
  "subject": "fil",
  "tema": "Philosophy · M",
  "title": "Reality: what is there and what is it like?",
  "md": "# Reality: what is there and what is it like?\n## Metaphysics\n- Asks **what exists** and what it is ultimately like\n- *Ta meta ta physika*; Aristotle’s ‘**first philosophy**’\n- **Ontology**: what kinds of things exist\n- Criticisms: **Kant** and the **Vienna Circle**\n## Appearance and reality\n- **Parmenides**: being is one and unchanging; change is appearance\n- **Plato**: the **sensible** world and the world of the **Forms**\n- **Bostrom**: the **simulation** argument\n## What is everything made of?\n- **Monism** (Spinoza), **dualism** (Descartes), **pluralism** (Empedocles, Leibniz)\n- **Materialism**: everything is matter (Democritus, Hobbes, physicalism)\n- **Idealism**: ‘to be is to be perceived’ (**Berkeley**)\n## Substance, essence and existence\n- **Aristotle**: **substance** and its **accidents**\n- **Hylomorphism**: **matter** + **form**\n- **Actuality** and **potentiality**: this is how change is explained\n- **Sartre**: ‘existence precedes essence’\n## Mind, body and AI\n- **Dualism**: how do they interact? (Elisabeth of Bohemia)\n- **Identity theory**: brain states\n- **Functionalism** (Putnam): the mind is defined by its function\n- The **Turing test** versus the **Chinese room** (Searle)\n- The **hard problem** of consciousness (Chalmers)\n## Time and change\n- **Heraclitus**: everything changes (the river)\n- **Zeno**: Achilles and the tortoise\n- The **ship of Theseus** (Plutarch): is it still the same?\n- **Newton** (absolute time) versus **Leibniz** (relative); **Einstein**\n- **Presentism** and **eternalism**\n## Are we free?\n- **Determinism** (Laplace’s demon) and **indeterminism**\n- **Hard determinism**: freedom is an illusion\n- **Libertarianism**: we could have acted otherwise\n- **Compatibilism**: being free is acting without **coercion**\n## Does God exist?\n- **Ontological** argument (Anselm)\n- **Cosmological** argument (the five ways) and the argument from **design** (Paley)\n- Against: the **problem of evil**; response: **theodicy**\n- A case apart: **Pascal’s wager**\n- **Theism**, **atheism**, **agnosticism** and **fideism**"
 },
 "map-fil-cuerpo-mente": {
  "subject": "fil",
  "tema": "Philosophy · Topic 2",
  "title": "The body and the mind",
  "md": "# Body and mind\n## The mind–body problem\n- Are we **one** thing or **two**?\n## Dualism (two realities)\n- **Material** body + **immaterial** soul (what is essential)\n- **Plato** — immortal soul, body as ‘prison’; winged chariot; soul in 3 parts (rational, spirited, appetitive)\n- **Descartes** — res cogitans (mind) vs res extensa (body-machine)\n## Materialist monism (one reality)\n- There is only **body**; the mind is its **activity** (the brain)\n- **Democritus**, **Hobbes**, **La Mettrie** (man a machine); today, **Dennett** and the **Churchlands**\n## The problems\n- Dualism: how do mind and body communicate?\n- Monism: are we **free** or just chemistry?"
 }
};
